/**
 * Shared primitives used across every endpoint contract.
 *
 * Owner: E (integration). Additive-only once published — adding an optional
 * field is free, renaming or removing one breaks four workstreams silently.
 */
import { z } from 'zod';

export const UuidSchema = z.string().uuid();

/**
 * Human-facing short code shown on the confirmation screen ("Report #A2F4C").
 * Generated by B on insert. Citizens quote this, not the uuid.
 */
export const TicketIdSchema = z.string().regex(/^[0-9A-Z]{5}$/);

/**
 * A location as the browser reports it. Stored as geography(Point,4326) in
 * Postgres — never as two loose floats, because the clustering query needs
 * PostGIS. Wire format stays lat/lng for readability.
 */
export const GeoPointSchema = z.object({
  lat: z.number().min(-90).max(90),
  lng: z.number().min(-180).max(180),
});
export type GeoPoint = z.infer<typeof GeoPointSchema>;

/**
 * Browser GPS accuracy in metres, straight from getCurrentPosition().coords.
 * A drives the adaptive clustering radius (PRD §6), so A must send it even
 * though the citizen never sees it. Capped at 500m — beyond that the fix is
 * useless and the radius would swallow the whole neighbourhood.
 */
export const GpsAccuracySchema = z.number().min(0).max(500);

/** ISO 8601 timestamp. */
export const TimestampSchema = z.string().datetime();

/**
 * Cursor pagination, not offset. Offset paging shifts rows under the reader when
 * the cron rewrites priority_score mid-scroll, which the admin queue does every
 * five minutes.
 */
export function paged<T extends z.ZodTypeAny>(item: T) {
  return z.object({
    items: z.array(item),
    next_cursor: z.string().nullable(),
    total: z.number().int().nonnegative().optional(),
  });
}

export const PageQuerySchema = z.object({
  cursor: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
});
export type PageQuery = z.infer<typeof PageQuerySchema>;

/** Every non-2xx response from every endpoint has this body. */
export const ApiErrorSchema = z.object({
  error: z.object({
    code: z.enum([
      'VALIDATION_FAILED',
      'UNAUTHORIZED',
      'FORBIDDEN',
      'NOT_FOUND',
      'RATE_LIMITED',
      'ILLEGAL_TRANSITION',
      'CONFLICT',
      'INTERNAL',
    ]),
    message: z.string(),
    /** Field-level detail for VALIDATION_FAILED, keyed by path. */
    fields: z.record(z.string(), z.string()).optional(),
    /** Seconds until the caller may retry. Set on RATE_LIMITED. */
    retry_after_s: z.number().int().optional(),
  }),
});
export type ApiError = z.infer<typeof ApiErrorSchema>;
